dist: trusty
language: node_js
node_js:
  - '8.8.1'

script:
  - npm run test

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable fluxbox

cache:
  directories:
    - node_modules

env:
  - TEST_HOST_STORYBOOK_PORT=9999
  - TEST_HOST_STORYBOOK_URL=http://localhost:9999

before_script:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - sleep 3
