# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.16.3'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install (with build included)'

- script: |
    npm test	
  displayName: 'Test'

- script: |
    npm run build-storybook
  displayName: 'Build static storybook'

- bash: |
    ./scripts/branch-deployment.sh
  displayName: 'Gh-Pages - Push Featurebranch'
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
    PR_SOURCE_BRANCH_NAME: $(System.PullRequest.SourceBranch)
    SOURCE_BRANCH_NAME: $(Build.SourceBranchName)

- bash: |
    ./scripts/branch-deployment-notifier.sh
  displayName: 'Gh-Pages - Notify Users about successful deployment'
  env:
    SLACK_TOKEN: $(SLACK_TOKEN)
    BRANCH_NAME: $(System.PullRequest.SourceBranch)

- task: CopyFiles@2
  displayName: 'Stage Artifacts'
  inputs:
    SourceFolder: ./storybook-static
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'drop'
    targetPath: '$(Build.ArtifactStagingDirectory)'
