# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.15.3'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'install & build'

- script: |
    npm test
  displayName: 'test'

- script: |
    npm run build-storybook
  displayName: 'build storybook'

- task: CopyFiles@2
  displayName: 'Stage Artifacts'
  inputs:
    SourceFolder: ./storybook-static
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'drop'
    targetPath: '$(Build.ArtifactStagingDirectory)'
